### ISSUE TITLE
Add Tiddlywiki and its desktop app TidGi

### ISSUE THREAD

**Issue by linonetwo** [schickling/awesome-local-first#1]
I think they are good examples of fully opensourced localfirst apps.

[Tiddlywiki](https://github.com/Jermolene/TiddlyWiki5) - A self-contained JavaScript wiki for the browser, Node.js, AWS Lambda etc.

[TidGi](https://github.com/tiddly-gittly/TidGi-Desktop) - Customizable personal knowledge-base with git as backup manager.

**Comment by ghost** [comment]
Hi @linonetwo, how are you ?!

I hope to help and I hope you enjoy this pr. I've added tiddlywiki here to this repository. I made an initial [pull-request](https://github.com/schickling/awesome-local-first/pull/4) to resolve this [issue](https://github.com/schickling/awesome-local-first/issues/1), I await your contact for further guidance.

**Comment by linonetwo** [comment]
You are very welcome, thanks.

**Comment by ghost** [comment]
Hi @linonetwo.

> You are very welcome, thanks.

thanks you for comment. Please, see this: [awesome-local-first/pull/4](https://github.com/schickling/awesome-local-first/pull/4). I've done it on this pull-request, now. Could you check it out?

**Comment by ghost** [comment]
thank you @schickling, @linonetwo.
