### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by ghost** [schickling/awesome-local-first#9]
Hi,

I would like to suggest some alternatives, how to disable these options: `[Releases](https://github.com/schickling/awesome-local-first/releases)`, `[Packages](https://github.com/users/schickling/packages?repo_name=awesome-local-first)`

***img-before***
![image](https://github.com/schickling/awesome-local-first/assets/154566915/3e7ebb5d-cda2-4415-972b-0b1327e67032)

***img-after***
![image](https://github.com/schickling/awesome-local-first/assets/154566915/f10ac6d3-59a2-4c5b-82cf-7f04bb24c32c)

***What do you think of this idea?***

**Comment by schickling** [comment]
Done :)

**Comment by ghost** [comment]
Hi @schickling, how are you? thanks!
